# Generated by Django 5.2.6 on 2025-09-22 12:09

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(help_text='CPF do usuário (11 dígitos)', max_length=11, unique=True)),
                ('nome', models.CharField(help_text='Nome completo do usuário', max_length=200)),
                ('email', models.EmailField(help_text='Email do usuário', max_length=254, unique=True)),
                ('nome_usuario', models.CharField(help_text='Nome de usuário para fazer login', max_length=150, unique=True)),
                ('tipo_usuario', models.IntegerField(default=0, help_text='Tipo: 0=Usuário comum, 1=Administrador')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento do usuário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação da conta')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id_artigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Título do artigo', max_length=200)),
                ('descricao', models.TextField(help_text='Conteúdo completo do artigo')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do artigo (opcional)', null=True, upload_to='artigos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Usuário que criou o artigo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Artigos',
            },
        ),
        migrations.CreateModel(
            name='Editais',
            fields=[
                ('id_edital', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Título do edital', max_length=200)),
                ('descricao', models.TextField(help_text='Conteúdo do edital')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do edital', null=True, upload_to='editais/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Autor do edital', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Título da notícia', max_length=200)),
                ('descricao', models.TextField(help_text='Conteúdo completo da notícia')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da notícia (opcional)', null=True, upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Usuário que criou a notícia', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notícias',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(help_text='Texto do comentário')),
                ('data_comentario', models.DateTimeField(auto_now_add=True, help_text='Data do comentário')),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.artigos')),
                ('autor', models.ForeignKey(help_text='Autor do comentário', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.editais')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.noticias')),
            ],
            options={
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
