# Generated by Django 5.2.6 on 2025-09-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today, help_text='Data de nascimento do usuário'),
        ),
    ]
